[package]
name = "openai-api-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json","multipart"] }
serde = { version = "1.0", features = ["derive"] }
async-trait = "0.1.66"

[dev-dependencies]
toml = "0.7.2"
pretty_assertions = "1"
tokio = { version = "1", features = ["full"] }